[package]
name = "cargo-unleash"
version = "1.0.0-alpha.10"
authors = ["Benjamin Kampmann <ben@gnunicorn.org>"]
edition = "2018"
license = "GPL-3.0"
repository ="https://github.com/gnunicorn/cargo-unleash"
description = "Tooling to manage releasing of crates in massiv workspaces/monorepos"
readme = "Readme.md"
keywords = ["cargo", "publishing", "unleash", "workspaces", "monorepo"]
categories = ["development-tools", "development-tools::cargo-plugins", ]

exclude = [".gitignore", ".github/**"]

[[bin]]
name = "cargo-unleash"
path = "src/main.rs"

[dependencies]
structopt = "0.3.9"
toml_edit = "0.1.3"
log = "0.4.8"
flexi_logger = "0.14.8"
petgraph = "0.5.0"
regex = "1.3.4"
reqwest = { version = "0.10.3", features = ["json"] }
tokio = { version = "0.2.11", default_features = false }
futures = "0.3.4"
serde = "1.0"

# CARGO VERSION BOUND dependencies
cargo = "0.43.1"
semver = "0.9.0"
flate2 = "1.0.3"
tar = "0.4.18"
